[features]
seeds = false
skip-lint = false
[programs.localnet]
pass_manager = "3ctQK81JTmfdGivAM3kaioHxmf4naGcSkzFFy9i1vaec"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/divyanshgupta/Hackathon/wallets/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
