import React from "react";
import Head from "next/head";
import styles from "../styles/Landing.module.css";
//components
import NavbarMenu from "../components/Landing/navbar";
import Banner from "../components/Landing/Banner";
import CountUpp from "../components/Landing/countUp";
import About from "../components/Landing/About";
import Footer from "../components/Landing/Footer";
import Features from "../components/Landing/Features/index";
import WhyChoose from "../components/Landing/WhyChoose";

export default function Home() {
  return (
    <div className={styles.container}>
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavbarMenu />

      <main>
        <div>
          <Banner />

          <CountUpp />
          <WhyChoose />
          <About />
          <Features />
        </div>
      </main>

      <Footer />
    </div>
  );
}
